- frontend/package.json
- frontend/src/components/SocialShares/index.module.css
- frontend/src/components/SocialShares/index.tsx
- frontend/src/pages/PollPage/ActivePoll.tsx
- frontend/src/pages/PollPage/CompletedPoll.tsx
- frontend/src/pages/PollPage/ThanksForVoting.tsx
- pnpm-lock.yaml
The active part is done here
(i.e. talking to the social sites);
what is left is preparing the needed metadata
for harvesters to generate the proper thumbnail/preview.
That will be done separately.
> Implement the basics for social sharing

- frontend/src/components/PollCard/PollAccessIndicator.tsx
- frontend/src/components/PollCard/index.tsx
- frontend/src/components/icons/BrokenPollAccessIcon.tsx
- frontend/src/components/icons/ClosedPollIcon.tsx
- frontend/src/components/icons/MyPollIcon.tsx
- frontend/src/components/icons/index.module.css
- frontend/src/hooks/PermissionCache.ts
- frontend/src/hooks/useExtendedPoll.ts
- frontend/src/hooks/usePollPermissions.ts
- frontend/src/pages/DashboardPage/useDashboardData.ts
- frontend/src/pages/PollPage/ActivePoll.tsx
- frontend/src/pages/PollPage/CompletedPoll.tsx
- frontend/src/pages/PollPage/ThanksForVoting.tsx
- frontend/src/pages/PollPage/hook.ts
- frontend/src/utils/bignumberify.js
- frontend/src/utils/poll.utils.ts
Poll permission data will be cached, and the cache is regularly saved to browser local store.
Therefore, normally, every pill will be checked by every wallet only once.
> Add permanent caching for poll permissions

- contracts/src/chains.ts
- contracts/src/xchain.ts
- hardhat/hardhat.config.ts
- hardhat/package.json
- hardhat/tasks/deploy.ts
- pnpm-lock.yaml
* Adds deterministic deployment - won't re-deploy contracts unless something has changed
* Adds base chain
> Deterministic deployment & Base chain

- frontend/src/components/PollCard/index.tsx
- frontend/src/constants/config.ts
- frontend/src/hooks/useExtendedPoll.ts
- frontend/src/hooks/usePollGaslessStatus.ts
- frontend/src/hooks/usePollPermissions.ts
- frontend/src/pages/DashboardPage/index.tsx
- frontend/src/pages/DashboardPage/useDashboardData.ts
- frontend/src/pages/PollPage/hook.ts
Make it so that all optional features of the dashboard can be configured from config.ts. 
(Should we load the gasless status, or the results, or the permissions, for each cards? Do we want filtering? etc)
> Feature flags for the dashboard

- frontend/package.json
- frontend/src/components/PollCard/PollAccessIndicator.tsx
- frontend/src/components/PollCard/index.tsx
- frontend/src/hooks/PermissionCache.ts
- frontend/src/hooks/useExtendedPoll.ts
- frontend/src/hooks/useIPFSData.ts
- frontend/src/hooks/usePollPermissions.ts
- frontend/src/pages/DashboardPage/useDashboardData.ts
- frontend/src/pages/PollPage/ActivePoll.tsx
- frontend/src/pages/PollPage/CompletedPoll.tsx
- frontend/src/pages/PollPage/ThanksForVoting.tsx
- frontend/src/pages/PollPage/hook.ts
- frontend/src/utils/Pinata.ts
- frontend/src/utils/StoredLRUCache.ts
- frontend/src/utils/poll.utils.ts
- pnpm-lock.yaml
Use a permanent cache for IPFS data (like permissions), and other improvements.
> Improve caching all over the place

- frontend/src/components/InputFields/InputField.tsx
- frontend/src/components/InputFields/Label.tsx
- frontend/src/components/InputFields/useInputField.ts
- frontend/src/components/InputFields/useLabel.ts
- frontend/src/components/InputFields/util.ts
- Label: support restricting to an enum-like types
- Form validation: properly pass down `isStillFresh()` to validators
> More form improvements

- hardhat/tasks/deploy.ts
If we find an address in the previous env file,
but the tx is not really there, just forget it
and deploy.
> Fix contract deployment logic

- frontend/src/hooks/useExtendedPoll.ts
- frontend/src/hooks/usePollPermissions.ts
- frontend/src/pages/PollPage/ActivePoll.tsx
- frontend/src/pages/PollPage/hook.ts
Display the big warning icon animated, only after
permission testing is finished.
> Nicer displaying of permission issue

- frontend/src/components/Animations/index.tsx
- frontend/src/components/InputFields/FieldStatusIndicator.tsx
- frontend/src/components/InputFields/ProblemAndValidationMessage.tsx
- frontend/src/components/InputFields/ProblemDisplay.tsx
- frontend/src/components/InputFields/TextArrayInput.tsx
- frontend/src/components/InputFields/WithVisibility.tsx
- frontend/src/components/PollCard/index.tsx
- frontend/src/constants/config.ts
- frontend/src/main.tsx
- frontend/src/pages/DashboardPage/NoPolls.tsx
- frontend/src/pages/PollPage/ActivePoll.tsx
- frontend/src/pages/PollPage/BigCountdown.tsx
- frontend/src/pages/PollPage/CompletedPoll.tsx
- frontend/src/pages/PollPage/ThanksForVoting.tsx
Also, default some things by default
> Make it possible to configure which animations do we want 

- frontend/src/components/ACLs/allowAll.ts
- frontend/src/components/ACLs/allowList.ts
- frontend/src/components/ACLs/common.ts
- frontend/src/components/ACLs/index.module.css
- frontend/src/components/ACLs/index.ts
- frontend/src/components/ACLs/tokenHolder.ts
- frontend/src/components/ACLs/xchain.ts
- frontend/src/components/InputFields/useOneOfField.ts
- frontend/src/components/InputFields/validation.ts
- frontend/src/hooks/usePollPermissions.ts
- frontend/src/pages/CreatePollPage/index.module.css
- frontend/src/pages/CreatePollPage/useCreatePollForm.ts
- frontend/src/utils/poll.utils.ts
All the logic relevant to specific ACLs have been moved separate files to src/components/ACLs.
This should make it easier to test individual ACLs, and to add new ones.
> Refactor ACL handling

- frontend/src/components/InputFields/useInputField.ts
- frontend/src/components/VoteBrowser/VoteBrowser.tsx
- frontend/src/components/VoteBrowser/index.module.css
- frontend/src/components/VoteBrowser/useVoteBrowserData.ts
- frontend/src/hooks/useExtendedPoll.ts
- frontend/src/pages/PollPage/CompletedPoll.tsx
- frontend/src/pages/PollPage/ThanksForVoting.tsx
- frontend/src/types/poll.ts
Add a proper table for displaying the individual votes,
with filter, search, and proper formatting.
> Improve votes display

- frontend/src/components/ACLs/xchain.tsx
- frontend/src/components/ConnectedAccount/index.module.css
- frontend/src/constants/config.ts
- frontend/src/hooks/PermissionCache.ts
- frontend/src/hooks/useExtendedPoll.ts
- frontend/src/pages/PollPage/ActivePoll.tsx
- frontend/src/pages/PollPage/hook.ts
- frontend/src/utils/StoredLRUCache.ts
- frontend/src/utils/bignumberify.js
- frontend/src/utils/react.utils.ts
- frontend/src/utils/string.utils.ts
- More adjustments on the connected wallet button
- Support triggering permission re-check on poll page
- Link to referenced tokens in xchain poll setup and error message
- Internal changes
> Various improvements

- frontend/src/components/ConnectWallet/index.tsx
- frontend/src/components/ConnectedAccount/index.module.css
- frontend/src/components/ConnectedAccount/index.tsx
- frontend/src/components/PollCard/index.tsx
- frontend/src/constants/config.ts
- frontend/src/providers/Web3Context.ts
- frontend/src/providers/Web3Provider.tsx
- frontend/src/utils/crypto.demo.ts
* Internal fixes
* In the connected wallet widget, show chain logo instead of short name. Expand on hover.
* By default, hide poll cards with any errors
> Random improvements

- frontend/src/components/ACLs/allowAll.ts
- frontend/src/components/ACLs/allowList.ts
- frontend/src/components/ACLs/common.ts
- frontend/src/components/ACLs/tokenHolder.tsx
- frontend/src/components/ACLs/xchain.tsx
- frontend/src/pages/CreatePollPage/useCreatePollForm.ts
- frontend/src/utils/poll.utils.ts
Properly configure vote weighting options
when creating polls with token holder or xchain ACLs.
> Use the new weight options

- contracts/src/types.ts
- frontend/src/components/PollCard/index.tsx
- frontend/src/constants/config.ts
- frontend/src/hooks/useExtendedPoll.ts
- frontend/src/pages/PollPage/ActivePoll.tsx
- frontend/src/utils/poll.utils.ts
This data is available at multiple locations. On-chain storage is expensive, so removing redundancy.
> Remove useless redundant data

- README.md
- Update name
- Also mention running against testnet
- Replace the reference to Vue with React
> Update details in README

- frontend/src/components/Layout/index.module.css
- frontend/src/components/Layout/index.tsx
- frontend/src/components/icons/LogoIcon.tsx
- frontend/src/pages/DashboardPage/index.module.css
Small updates based on feedback from Jure.
> Small updates on the mobile UI

- frontend/src/main.tsx
Opening /lido should redirect vote-lido.oasis.io
> Add redirect to lido

- frontend/src/constants/config.ts
The following two settings can now be customized from .env:
- Hide "under construction" features
- Hide hardwired settings
> Add more customization options

- frontend/package.json
- frontend/src/components/ConnectedAccount/index.tsx
- frontend/src/components/Dialog/dialog.tsx
- frontend/src/index.css
- frontend/src/providers/EthereumContext.ts
- frontend/src/providers/EthereumProvider.tsx
- pnpm-lock.yaml
Offer "copy address", "view in explorer", "disconnect wallet"
features, instead of just copying the address.
It looks like this: 
On mobile:
Closes #161.
> Show wallet dialog when connecting on address

- frontend/src/components/Layout/index.module.css
- frontend/src/components/Layout/index.tsx
- frontend/src/components/LayoutBase/index.module.css
- frontend/src/components/LayoutBase/index.tsx
- frontend/src/pages/DashboardPage/index.module.css
- frontend/src/pages/LandingPage/index.module.css
- frontend/src/pages/LandingPage/index.tsx
- General: vertical centering should work better now
- Mobile: eliminate horizontal scrolling
|Before | After |
| -------- | -------- |
| <img width="419" height="709" alt="image" src="https://github.com/user-attachments/assets/3b5a5939-ed47-4c55-a239-f80bf5214704" /> |  <img width="418" height="708" alt="image" src="https://github.com/user-attachments/assets/8411f2bb-906b-4d23-86ab-34d3acc2f088" />  |
|  <img width="1381" height="708" alt="image" src="https://github.com/user-attachments/assets/e07bf53a-449c-489b-80ec-94855d29b405" />  |  <img width="1383" height="704" alt="image" src="https://github.com/user-attachments/assets/b34ff891-b40d-41fe-8fcb-794868678e48" />  |
> Improve landing page layout

- frontend/src/components/InputFields/index.module.css
- frontend/src/components/Layout/index.tsx
> Fix some CSS issues introduced by introducing TailWind
